// Wine data — enhanced with WineMag 130k dataset
// 12 countries, 67 regions, 15-20 producers per region, 26 varietals

export const COUNTRIES = [
  { id: "france", name: "France", emoji: "\u{1F1EB}\u{1F1F7}", world: "old" },
  { id: "italy", name: "Italy", emoji: "\u{1F1EE}\u{1F1F9}", world: "old" },
  { id: "spain", name: "Spain", emoji: "\u{1F1EA}\u{1F1F8}", world: "old" },
  { id: "portugal", name: "Portugal", emoji: "\u{1F1F5}\u{1F1F9}", world: "old" },
  { id: "germany", name: "Germany", emoji: "\u{1F1E9}\u{1F1EA}", world: "old" },
  { id: "austria", name: "Austria", emoji: "\u{1F1E6}\u{1F1F9}", world: "old" },
  { id: "usa", name: "United States", emoji: "\u{1F1FA}\u{1F1F8}", world: "new" },
  { id: "argentina", name: "Argentina", emoji: "\u{1F1E6}\u{1F1F7}", world: "new" },
  { id: "chile", name: "Chile", emoji: "\u{1F1E8}\u{1F1F1}", world: "new" },
  { id: "australia", name: "Australia", emoji: "\u{1F1E6}\u{1F1FA}", world: "new" },
  { id: "new_zealand", name: "New Zealand", emoji: "\u{1F1F3}\u{1F1FF}", world: "new" },
  { id: "south_africa", name: "South Africa", emoji: "\u{1F1FF}\u{1F1E6}", world: "new" },
];

export const REGIONS = {
  france: [
    { id: "burgundy", name: "Burgundy" }, { id: "bordeaux", name: "Bordeaux" },
    { id: "champagne", name: "Champagne" }, { id: "rhone", name: "Rh\u00f4ne Valley" },
    { id: "loire", name: "Loire Valley" }, { id: "alsace", name: "Alsace" },
    { id: "provence", name: "Provence" }, { id: "languedoc", name: "Languedoc-Roussillon" },
    { id: "beaujolais", name: "Beaujolais" }, { id: "southwest_france", name: "Southwest France" },
  ],
  italy: [
    { id: "tuscany", name: "Tuscany" }, { id: "piedmont", name: "Piedmont" },
    { id: "veneto", name: "Veneto" }, { id: "sicily", name: "Sicily" },
    { id: "puglia", name: "Puglia / Southern Italy" }, { id: "trentino", name: "Trentino-Alto Adige" },
    { id: "campania", name: "Campania" },
  ],
  spain: [
    { id: "rioja", name: "Rioja" }, { id: "ribera", name: "Ribera del Duero" },
    { id: "priorat", name: "Priorat" }, { id: "rias_baixas", name: "R\u00edas Baixas" },
    { id: "jerez", name: "Jerez (Sherry)" }, { id: "penedes", name: "Pened\u00e8s" },
    { id: "rueda", name: "Rueda" },
  ],
  usa: [
    { id: "napa", name: "Napa Valley" }, { id: "sonoma", name: "Sonoma" },
    { id: "willamette", name: "Willamette Valley" }, { id: "paso_robles", name: "Paso Robles" },
    { id: "santa_barbara", name: "Santa Barbara" }, { id: "finger_lakes", name: "Finger Lakes" },
    { id: "walla_walla", name: "Walla Walla" },
  ],
  south_africa: [
    { id: "stellenbosch", name: "Stellenbosch" }, { id: "constantia", name: "Constantia" },
    { id: "franschhoek", name: "Franschhoek" }, { id: "swartland", name: "Swartland" },
    { id: "walker_bay", name: "Walker Bay" }, { id: "paarl", name: "Paarl" },
  ],
  argentina: [
    { id: "mendoza", name: "Mendoza" }, { id: "salta", name: "Salta / Cafayate" },
    { id: "patagonia_ar", name: "Patagonia" },
  ],
  chile: [
    { id: "maipo", name: "Maipo Valley" }, { id: "colchagua", name: "Colchagua Valley" },
    { id: "casablanca", name: "Casablanca Valley" }, { id: "aconcagua", name: "Aconcagua" },
  ],
  australia: [
    { id: "barossa", name: "Barossa Valley" }, { id: "mclaren", name: "McLaren Vale" },
    { id: "yarra", name: "Yarra Valley" }, { id: "margaret_river", name: "Margaret River" },
    { id: "hunter", name: "Hunter Valley" }, { id: "coonawarra", name: "Coonawarra" },
  ],
  new_zealand: [
    { id: "marlborough", name: "Marlborough" }, { id: "central_otago", name: "Central Otago" },
    { id: "hawkes_bay", name: "Hawke's Bay" },
  ],
  portugal: [
    { id: "douro", name: "Douro Valley" }, { id: "alentejo", name: "Alentejo" },
    { id: "dao", name: "D\u00e3o" }, { id: "vinho_verde", name: "Vinho Verde" },
  ],
  germany: [
    { id: "mosel", name: "Mosel" }, { id: "rheingau", name: "Rheingau" },
    { id: "pfalz", name: "Pfalz" }, { id: "baden", name: "Baden" },
    { id: "rheinhessen", name: "Rheinhessen" },
  ],
  austria: [
    { id: "wachau", name: "Wachau" }, { id: "kamptal", name: "Kamptal" },
    { id: "burgenland", name: "Burgenland" },
  ],
};

export const ESTATES = {
  burgundy: [
    { id: "domaine_romanee_conti", name: "Domaine de la Romanée-Conti" },
    { id: "domaine_leroy", name: "Domaine Leroy" },
    { id: "maison_louis_jadot", name: "Maison Louis Jadot" },
    { id: "domaine_faiveley", name: "Domaine Faiveley" },
    { id: "domaine_armand_rousseau", name: "Domaine Armand Rousseau" },
    { id: "domaine_des_lambrays", name: "Domaine des Lambrays" },
    { id: "domaine_jean_grivot", name: "Domaine Jean Grivot" },
    { id: "clos_de_tart", name: "Clos de Tart" },
    { id: "domaine_leflaive", name: "Domaine Leflaive" },
    { id: "domaine_nicolas_rossignol", name: "Domaine Nicolas Rossignol" },
    { id: "domaine_pinson", name: "Domaine Pinson" },
    { id: "domaine_parent", name: "Domaine Parent" },
    { id: "domaine_drouhinlaroze", name: "Domaine Drouhin-Laroze" },
    { id: "domaine_perrotminot", name: "Domaine Perrot-Minot" },
    { id: "domaine_du_comte_ligerbelair", name: "Domaine du Comte Liger-Belair" },
    { id: "domaine_buisson_battault", name: "Domaine Buisson Battault" },
    { id: "chateau_fuisse", name: "Château Fuissé" },
    { id: "domaine_dujac", name: "Domaine Dujac" },
  ],
  bordeaux: [
    { id: "chateau_mouton_rothschild", name: "Château Mouton Rothschild" },
    { id: "chateau_lafite_rothschild", name: "Château Lafite Rothschild" },
    { id: "chateau_margaux", name: "Château Margaux" },
    { id: "chateau_petrus", name: "Château Pétrus" },
    { id: "chateau_climens", name: "Château Climens" },
    { id: "chateau_leoville_barton", name: "Château Léoville Barton" },
    { id: "chateau_dyquem", name: "Château d'Yquem" },
    { id: "vieux_chateau_certan", name: "Vieux Château Certan" },
    { id: "chateau_pontetcanet", name: "Château Pontet-Canet" },
    { id: "chateau_trotanoy", name: "Château Trotanoy" },
    { id: "chateau_hautbrion", name: "Château Haut-Brion" },
    { id: "le_dome", name: "Le Dôme" },
    { id: "chateau_leoville_poyferre", name: "Château Léoville Poyferré" },
    { id: "chateau_latour", name: "Château Latour" },
    { id: "chateau_palmer", name: "Château Palmer" },
    { id: "chateau_ausone", name: "Château Ausone" },
    { id: "chateau_lynchbages", name: "Château Lynch-Bages" },
    { id: "chateau_la_mission_hautbrion", name: "Château La Mission Haut-Brion" },
  ],
  champagne: [
    { id: "dom_perignon", name: "Dom Pérignon" },
    { id: "veuve_clicquot", name: "Veuve Clicquot" },
    { id: "taittinger", name: "Taittinger" },
    { id: "ruinart", name: "Ruinart" },
    { id: "moet_chandon", name: "Moët & Chandon" },
    { id: "salon", name: "Salon" },
    { id: "larmandierbernier", name: "Larmandier-Bernier" },
    { id: "krug", name: "Krug" },
    { id: "louis_roederer", name: "Louis Roederer" },
    { id: "jacquesson_et_fils", name: "Jacquesson et Fils" },
    { id: "henriot", name: "Henriot" },
    { id: "pol_roger", name: "Pol Roger" },
    { id: "billecartsalmon", name: "Billecart-Salmon" },
    { id: "pehusimonet", name: "Pehu-Simonet" },
    { id: "deutz", name: "Deutz" },
    { id: "philipponnat", name: "Philipponnat" },
    { id: "lanson", name: "Lanson" },
    { id: "bollinger", name: "Bollinger" },
  ],
  rhone: [
    { id: "m_chapoutier", name: "M. Chapoutier" },
    { id: "chateau_de_beaucastel", name: "Château de Beaucastel" },
    { id: "domaine_du_vieux_telegraphe", name: "Domaine du Vieux Télégraphe" },
    { id: "domaine_de_la_janasse", name: "Domaine de la Janasse" },
    { id: "domaine_des_carteresses", name: "Domaine des Carteresses" },
    { id: "michel_stephane_ogier", name: "Michel & Stéphane Ogier" },
    { id: "eric_joel_durand", name: "Éric & Jöel Durand" },
    { id: "lamandine", name: "L'Amandine" },
    { id: "domaine_des_remizieres", name: "Domaine des Remizières" },
    { id: "gilles_flacher", name: "Gilles Flacher" },
    { id: "fayolle_fils_fille", name: "Fayolle Fils & Fille" },
    { id: "e_guigal", name: "E. Guigal" },
    { id: "domaine_jeanmichel_gerin", name: "Domaine Jean-Michel Gerin" },
    { id: "domaine_du_vieux_lazaret", name: "Domaine du Vieux Lazaret" },
    { id: "pierre_henri_morel", name: "Pierre Henri Morel" },
    { id: "chateau_daqueria", name: "Château d'Aqueria" },
    { id: "chateau_maucoil", name: "Château Maucoil" },
    { id: "tardieulaurent", name: "Tardieu-Laurent" },
  ],
  loire: [
    { id: "domaine_huet", name: "Domaine Huët" },
    { id: "chateau_pierrebise", name: "Château Pierre-Bise" },
    { id: "moulin_touchais", name: "Moulin Touchais" },
    { id: "domaine_bernard_fleuriet_et_fils", name: "Domaine Bernard Fleuriet et Fils" },
    { id: "daniel_chotard", name: "Daniel Chotard" },
    { id: "domaine_du_petit_metris", name: "Domaine du Petit Métris" },
    { id: "domaine_delaporte", name: "Domaine Delaporte" },
    { id: "alphonse_mellot", name: "Alphonse Mellot" },
    { id: "domaine_roger_christophe_moreux", name: "Domaine Roger & Christophe Moreux" },
    { id: "domaine_vacheron", name: "Domaine Vacheron" },
    { id: "bernard_baudry", name: "Bernard Baudry" },
    { id: "chateau_de_parnay", name: "Château de Parnay" },
    { id: "domaine_vigneauchevreau", name: "Domaine Vigneau-Chevreau" },
    { id: "domaine_de_lecu", name: "Domaine de l'Ecu" },
    { id: "yannick_amirault", name: "Yannick Amirault" },
  ],
  alsace: [
    { id: "julien_schaal", name: "Julien Schaal" },
    { id: "jean_biecher_fils", name: "Jean Biecher & Fils" },
    { id: "domaine_weinbach", name: "Domaine Weinbach" },
    { id: "domaine_zindhumbrecht", name: "Domaine Zind-Humbrecht" },
    { id: "biecher_schaal", name: "Biecher & Schaal" },
    { id: "domaine_marcel_deiss", name: "Domaine Marcel Deiss" },
    { id: "domaine_ostertag", name: "Domaine Ostertag" },
    { id: "domaine_schoffit", name: "Domaine Schoffit" },
    { id: "bestheim", name: "Bestheim" },
    { id: "domaine_bottgeyl", name: "Domaine Bott-Geyl" },
    { id: "domaine_barmesbuecher", name: "Domaine Barmès-Buecher" },
    { id: "trimbach", name: "Trimbach" },
    { id: "rene_mure", name: "René Muré" },
    { id: "domaine_jean_sipp", name: "Domaine Jean Sipp" },
    { id: "zusslin", name: "Zusslin" },
  ],
  provence: [
    { id: "domaine_de_la_begude", name: "Domaine de la Bégude" },
    { id: "domaine_la_bastide_blanche", name: "Domaine la Bastide Blanche" },
    { id: "chateau_vignelaure", name: "Château Vignelaure" },
    { id: "chateau_grand_boise", name: "Château Grand Boise" },
    { id: "chateau_de_pibarnon", name: "Chateau de Pibarnon" },
    { id: "la_bastide_blanche", name: "La Bastide Blanche" },
    { id: "chateau_vannieres", name: "Château Vannières" },
    { id: "louis_latour", name: "Louis Latour" },
    { id: "chateau_saintmaur", name: "Château Saint-Maur" },
    { id: "jcb", name: "JCB" },
    { id: "domaine_saintandre_de_figuiere", name: "Domaine Saint-André de Figuière" },
    { id: "chateau_sainte_marguerite", name: "Château Sainte Marguerite" },
    { id: "chateau_dollieres", name: "Château d'Ollières" },
    { id: "chateau_la_mascaronne", name: "Château la Mascaronne" },
    { id: "mas_de_gourgonnier", name: "Mas de Gourgonnier" },
  ],
  languedoc: [
    { id: "delmas", name: "Delmas" },
    { id: "mas_du_soleilla", name: "Mas du Soleilla" },
    { id: "delas_freres", name: "Delas Frères" },
    { id: "domaine_du_clos_des_fees", name: "Domaine du Clos des Fées" },
    { id: "mas_gabinele", name: "Mas Gabinèle" },
    { id: "jeanluc_colombo", name: "Jean-Luc Colombo" },
    { id: "gerard_bertrand", name: "Gérard Bertrand" },
    { id: "m_chapoutier", name: "M. Chapoutier" },
    { id: "domaine_cazes", name: "Domaine Cazes" },
    { id: "les_vignerons_de_tautavel_vingrau", name: "Les Vignerons de Tautavel Vingrau" },
    { id: "divi_elegancia", name: "Diví Elegància" },
    { id: "jeanluc_and_paul_aegerter", name: "Jean-Luc and Paul Aegerter" },
    { id: "hecht_bannier", name: "Hecht & Bannier" },
    { id: "bernard_magrez", name: "Bernard Magrez" },
    { id: "chateau_rivesblanques", name: "Château Rives-Blanques" },
  ],
  beaujolais: [
    { id: "domaine_du_comte_ligerbelair", name: "Domaine du Comte Liger-Belair" },
    { id: "domaine_de_cotes_remont", name: "Domaine de Côtes Rémont" },
    { id: "stephane_aviron", name: "Stéphane Aviron" },
    { id: "domaine_labruyere", name: "Domaine Labruyère" },
    { id: "louis_jadot", name: "Louis Jadot" },
    { id: "richard_rottiers", name: "Richard Rottiers" },
    { id: "domaines_dominique_piron", name: "Domaines Dominique Piron" },
    { id: "domaine_vincent_girardin", name: "Domaine Vincent Girardin" },
    { id: "chateau_des_jacques", name: "Château des Jacques" },
    { id: "domaine_chignard", name: "Domaine Chignard" },
    { id: "domaine_de_rocheguillon", name: "Domaine de Roche-Guillon" },
    { id: "chateau_de_fuisse", name: "Château de Fuissé" },
    { id: "domaine_dumas", name: "Domaine Dumas" },
    { id: "albert_bichot", name: "Albert Bichot" },
    { id: "lucien_lardy", name: "Lucien Lardy" },
  ],
  southwest_france: [
    { id: "domaine_cauhape", name: "Domaine Cauhapé" },
    { id: "domaine_coustarret", name: "Domaine Coustarret" },
    { id: "domaine_berthoumieu", name: "Domaine Berthoumieu" },
    { id: "chateau_de_gayon", name: "Château de Gayon" },
    { id: "alain_brumont", name: "Alain Brumont" },
    { id: "vignobles_brumont", name: "Vignobles Brumont" },
    { id: "chateau_lamartine", name: "Château Lamartine" },
    { id: "chateau_hautmonplaisir", name: "Château Haut-Monplaisir" },
    { id: "domaine_lancienne_cure", name: "Domaine l'Ancienne Cure" },
    { id: "chateau_vincens", name: "Château Vincens" },
    { id: "domaine_nigri", name: "Domaine Nigri" },
    { id: "chateau_de_corbiac", name: "Château de Corbiac" },
    { id: "mas_del_perie", name: "Mas del Périé" },
    { id: "chateau_peyros", name: "Château Peyros" },
    { id: "chateau_eugenie", name: "Château Eugénie" },
  ],
  tuscany: [
    { id: "marchesi_antinori", name: "Marchesi Antinori" },
    { id: "sassicaia", name: "Sassicaia" },
    { id: "castello_banfi", name: "Castello Banfi" },
    { id: "tenuta_dellornellaia", name: "Tenuta dell'Ornellaia" },
    { id: "casanova_di_neri", name: "Casanova di Neri" },
    { id: "fattoria_petrolo", name: "Fattoria Petrolo" },
    { id: "podere_laione", name: "Podere L'Aione" },
    { id: "castello_dei_rampolla", name: "Castello dei Rampolla" },
    { id: "poggio_di_sotto", name: "Poggio di Sotto" },
    { id: "il_paradiso_di_manfredi", name: "Il Paradiso di Manfredi" },
    { id: "contucci", name: "Contucci" },
    { id: "san_giusto_a_rentennano", name: "San Giusto a Rentennano" },
    { id: "tenuta_san_guido", name: "Tenuta San Guido" },
    { id: "gianni_brunelli", name: "Gianni Brunelli" },
    { id: "biondi_santi", name: "Biondi Santi" },
    { id: "fontodi", name: "Fontodi" },
    { id: "isole_e_olena", name: "Isole e Olena" },
    { id: "conti_costanti", name: "Conti Costanti" },
  ],
  piedmont: [
    { id: "bruno_giacosa", name: "Bruno Giacosa" },
    { id: "giacomo_conterno", name: "Giacomo Conterno" },
    { id: "paolo_scavino", name: "Paolo Scavino" },
    { id: "vietti", name: "Vietti" },
    { id: "mascarello_giuseppe_e_figlio", name: "Mascarello Giuseppe e Figlio" },
    { id: "gaja", name: "Gaja" },
    { id: "luciano_sandrone", name: "Luciano Sandrone" },
    { id: "podere_rocche_dei_manzoni", name: "Podere Rocche dei Manzoni" },
    { id: "cavallotto", name: "Cavallotto" },
    { id: "giuseppe_rinaldi", name: "Giuseppe Rinaldi" },
    { id: "schiavenza", name: "Schiavenza" },
    { id: "brovia", name: "Brovia" },
    { id: "guido_porro", name: "Guido Porro" },
    { id: "massolino", name: "Massolino" },
    { id: "cantina_bartolo_mascarello", name: "Cantina Bartolo Mascarello" },
    { id: "sottimano", name: "Sottimano" },
    { id: "comm_g_b_burlotto", name: "Comm. G. B. Burlotto" },
    { id: "poderi_aldo_conterno", name: "Poderi Aldo Conterno" },
  ],
  veneto: [
    { id: "dal_forno_romano", name: "Dal Forno Romano" },
    { id: "quintarelli", name: "Quintarelli" },
    { id: "ca_la_bionda", name: "Cà La Bionda" },
    { id: "tenute_salvaterra", name: "Tenute Salvaterra" },
    { id: "nino_franco", name: "Nino Franco" },
    { id: "le_fraghe", name: "Le Fraghe" },
    { id: "tenuta_chiccheri", name: "Tenuta Chiccheri" },
    { id: "cesari", name: "Cesari" },
    { id: "venturini_massimino", name: "Venturini Massimino" },
    { id: "centanni", name: "Cent'Anni" },
    { id: "il_colle", name: "Il Colle" },
    { id: "roccolo_grassi", name: "Roccolo Grassi" },
    { id: "tenuta_santa_maria_alla_pieve", name: "Tenuta Santa Maria alla Pieve" },
    { id: "pieropan", name: "Pieropan" },
    { id: "gini", name: "Gini" },
  ],
  sicily: [
    { id: "passopisciaro", name: "Passopisciaro" },
    { id: "biondi", name: "Biondi" },
    { id: "tenuta_delle_terre_nere", name: "Tenuta delle Terre Nere" },
    { id: "cos", name: "COS" },
    { id: "le_casematte", name: "Le Casematte" },
    { id: "pietradolce", name: "Pietradolce" },
    { id: "graci", name: "Graci" },
    { id: "palari", name: "Palari" },
    { id: "fattorie_romeo_del_castello", name: "Fattorie Romeo del Castello" },
    { id: "wiegner", name: "Wiegner" },
    { id: "abraxas", name: "Abraxas" },
    { id: "capichera", name: "Capichera" },
    { id: "girolamo_russo", name: "Girolamo Russo" },
    { id: "tornatore", name: "Tornatore" },
    { id: "benanti", name: "Benanti" },
  ],
  puglia: [
    { id: "guastaferro", name: "Guastaferro" },
    { id: "contrade_di_taurasi_lonardo", name: "Contrade di Taurasi - Lonardo" },
    { id: "terredora_di_paolo", name: "Terredora Di Paolo" },
    { id: "basilisco", name: "Basilisco" },
    { id: "montevetrano", name: "Montevetrano" },
    { id: "dangelo", name: "D'Angelo" },
    { id: "cantine_del_notaio", name: "Cantine del Notaio" },
    { id: "feudi_di_san_gregorio", name: "Feudi di San Gregorio" },
    { id: "villa_raiano", name: "Villa Raiano" },
    { id: "galardi", name: "Galardi" },
    { id: "i_favati", name: "I Favati" },
    { id: "tenuta_le_querce", name: "Tenuta Le Querce" },
    { id: "tenuta_del_portale", name: "Tenuta del Portale" },
    { id: "cantine_olivella", name: "Cantine Olivella" },
    { id: "san_martino", name: "San Martino" },
  ],
  trentino: [
    { id: "gravner", name: "Gravner" },
    { id: "radikon", name: "Radikon" },
    { id: "foradori", name: "Foradori" },
    { id: "borgo_del_tiglio", name: "Borgo del Tiglio" },
    { id: "raccaro", name: "Raccaro" },
    { id: "cesari", name: "Cesari" },
    { id: "terlan", name: "Terlan" },
    { id: "tenuta_san_leonardo", name: "Tenuta San Leonardo" },
    { id: "gump_markus_prackwieser", name: "Gump Markus Prackwieser" },
    { id: "ferrari", name: "Ferrari" },
    { id: "gini", name: "Gini" },
    { id: "mongarda", name: "Mongarda" },
    { id: "jacuss", name: "Jacùss" },
    { id: "maso_martis", name: "Maso Martis" },
    { id: "scubla", name: "Scubla" },
  ],
  campania: [
    { id: "mastroberardino", name: "Mastroberardino" },
    { id: "feudi_di_san_gregorio", name: "Feudi di San Gregorio" },
    { id: "terredora_di_paolo", name: "Terredora Di Paolo" },
    { id: "villa_raiano", name: "Villa Raiano" },
    { id: "antonio_caggiano", name: "Antonio Caggiano" },
    { id: "montevetrano", name: "Montevetrano" },
    { id: "galardi", name: "Galardi" },
    { id: "i_favati", name: "I Favati" },
    { id: "marisa_cuomo", name: "Marisa Cuomo" },
    { id: "cantine_astroni", name: "Cantine Astroni" },
    { id: "quintodecimo", name: "Quintodecimo" },
    { id: "benito_ferrara", name: "Benito Ferrara" },
    { id: "luigi_maffini", name: "Luigi Maffini" },
    { id: "villa_matilde", name: "Villa Matilde" },
    { id: "cantine_dell_angelo", name: "Cantine dell'Angelo" },
  ],
  rioja: [
    { id: "vinedos_de_paganos", name: "Viñedos de Paganos" },
    { id: "benjamin_de_rothschild_vega_sicilia_sa", name: "Benjamin de Rothschild & Vega Sicilia SA" },
    { id: "bodegas_roda", name: "Bodegas Roda" },
    { id: "pintia", name: "Pintia" },
    { id: "numanthia", name: "Numanthia" },
    { id: "teso_la_monja", name: "Teso La Monja" },
    { id: "la_rioja_alta", name: "La Rioja Alta" },
    { id: "liberalia", name: "Liberalia" },
    { id: "altos_del_terral", name: "Altos del Terral" },
    { id: "dominio_de_atauta", name: "Dominio de Atauta" },
    { id: "remirez_de_ganuza", name: "Remírez de Ganuza" },
    { id: "maurodos", name: "Maurodos" },
    { id: "descendientes_de_j_palacios", name: "Descendientes de J. Palacios" },
    { id: "paixar", name: "Paixar" },
    { id: "garcia_figuero", name: "García Figuero" },
  ],
  ribera: [
    { id: "altos_del_terral", name: "Altos del Terral" },
    { id: "dominio_de_atauta", name: "Dominio de Atauta" },
    { id: "garcia_figuero", name: "García Figuero" },
    { id: "bodegas_hidalgo", name: "Bodegas Hidalgo" },
    { id: "vega_sicilia", name: "Vega Sicilia" },
    { id: "astrales", name: "Astrales" },
    { id: "balbas", name: "Balbas" },
    { id: "emilio_moro", name: "Emilio Moro" },
    { id: "alion", name: "Alion" },
    { id: "valduero", name: "Valduero" },
    { id: "lleiroso", name: "Lleiroso" },
    { id: "pago_de_carraovejas", name: "Pago de Carraovejas" },
    { id: "dominio_basconcillos", name: "Dominio Basconcillos" },
    { id: "alidis", name: "Alidis" },
    { id: "val_sotillo", name: "Val Sotillo" },
  ],
  priorat: [
    { id: "clos_mogador", name: "Clos Mogador" },
    { id: "sangenis_i_vaque", name: "Sangenís I Vaqué" },
    { id: "vall_llach", name: "Vall Llach" },
    { id: "terroir_al_limit", name: "Terroir Al Límit" },
    { id: "ferrer_bobet", name: "Ferrer Bobet" },
    { id: "clos_berenguer_del_molar", name: "Clos Berenguer del Molar" },
    { id: "celler_pasanau", name: "Celler Pasanau" },
    { id: "clos_figueras", name: "Clos Figueras" },
    { id: "marco_abella", name: "Marco Abella" },
    { id: "domini_de_la_cartoixa", name: "Domini de la Cartoixa" },
    { id: "mas_den_gil", name: "Mas d'en Gil" },
    { id: "fuentes", name: "Fuentes" },
    { id: "trossos_del_priorat", name: "Trossos del Priorat" },
    { id: "genium_celler", name: "Genium Celler" },
    { id: "tosalet", name: "Tosalet" },
  ],
  rias_baixas: [
    { id: "as_laxas", name: "As Laxas" },
    { id: "granbazan", name: "Granbazán" },
    { id: "adega_dos_eidos", name: "Adega dos Eidos" },
    { id: "adegas_gran_vinum", name: "Adegas Gran Vinum" },
    { id: "morgadio", name: "Morgadío" },
    { id: "terras_gauda", name: "Terras Gauda" },
    { id: "mar_de_vinas", name: "Mar de Viñas" },
    { id: "la_gitana", name: "La Gitana" },
    { id: "pazo_de_senorans", name: "Pazo de Señorans" },
    { id: "val_do_sosego", name: "Val do Sosego" },
    { id: "finca_de_arantei", name: "Finca de Arantei" },
    { id: "nora", name: "Nora" },
    { id: "la_cana", name: "La Caña" },
    { id: "maior_de_mendoza", name: "Maior de Mendoza" },
    { id: "nessa", name: "Nessa" },
  ],
  jerez: [
    { id: "bodegas_hidalgo", name: "Bodegas Hidalgo" },
    { id: "gonzalez_byass", name: "González Byass" },
    { id: "lustau", name: "Lustau" },
    { id: "hidalgo", name: "Hidalgo" },
    { id: "williams_humbert", name: "Williams & Humbert" },
    { id: "bodegas_dios_baco_sl", name: "Bodegas Dios Baco S.L." },
    { id: "sandeman", name: "Sandeman" },
    { id: "pedro_romero", name: "Pedro Romero" },
    { id: "bodegas_yuste", name: "Bodegas Yuste" },
    { id: "delgado_zuleta", name: "Delgado Zuleta" },
    { id: "osborne", name: "Osborne" },
    { id: "harveys", name: "Harveys" },
  ],
  penedes: [
    { id: "clos_mogador", name: "Clos Mogador" },
    { id: "sangenis_i_vaque", name: "Sangenís I Vaqué" },
    { id: "vall_llach", name: "Vall Llach" },
    { id: "terroir_al_limit", name: "Terroir Al Límit" },
    { id: "gramona", name: "Gramona" },
    { id: "ferrer_bobet", name: "Ferrer Bobet" },
    { id: "clos_berenguer_del_molar", name: "Clos Berenguer del Molar" },
    { id: "celler_pasanau", name: "Celler Pasanau" },
    { id: "clos_figueras", name: "Clos Figueras" },
    { id: "vinyes_del_terrer", name: "Vinyes del Terrer" },
    { id: "raventos_i_blanc", name: "Raventós I Blanc" },
    { id: "marco_abella", name: "Marco Abella" },
    { id: "domini_de_la_cartoixa", name: "Domini de la Cartoixa" },
    { id: "mas_den_gil", name: "Mas d'en Gil" },
    { id: "fuentes", name: "Fuentes" },
  ],
  rueda: [
    { id: "vetus", name: "Vetus" },
    { id: "anier", name: "Anier" },
    { id: "12_linajes", name: "12 Linajes" },
    { id: "bodegas_y_vinedos_tabula", name: "Bodegas y Viñedos Tábula" },
    { id: "protos", name: "Protos" },
    { id: "campo_alegre", name: "Campo Alegre" },
    { id: "matarromera", name: "Matarromera" },
    { id: "blanco_nieva", name: "Blanco Nieva" },
    { id: "carlos_moro", name: "Carlos Moro" },
    { id: "telmo_rodriguez", name: "Telmo Rodríguez" },
    { id: "bodegas_riojanas", name: "Bodegas Riojanas" },
    { id: "comenge", name: "Comenge" },
    { id: "legaris", name: "Legaris" },
    { id: "marques_de_la_concordia", name: "Marqués de la Concordia" },
    { id: "beronia", name: "Beronia" },
  ],
  napa: [
    { id: "opus_one", name: "Opus One" },
    { id: "caymus", name: "Caymus" },
    { id: "robert_mondavi", name: "Robert Mondavi" },
    { id: "stags_leap_wine_cellars", name: "Stag's Leap Wine Cellars" },
    { id: "silver_oak", name: "Silver Oak" },
    { id: "far_niente", name: "Far Niente" },
    { id: "shafer", name: "Shafer" },
    { id: "cardinale", name: "Cardinale" },
    { id: "colgin", name: "Colgin" },
    { id: "dolce", name: "Dolce" },
    { id: "yao_ming", name: "Yao Ming" },
    { id: "arkenstone", name: "Arkenstone" },
    { id: "harlan_estate", name: "Harlan Estate" },
    { id: "montagna", name: "Montagna" },
    { id: "redmon", name: "Redmon" },
    { id: "macauley", name: "Macauley" },
    { id: "paul_hobbs", name: "Paul Hobbs" },
    { id: "tierra_roja", name: "Tierra Roja" },
  ],
  sonoma: [
    { id: "williams_selyem", name: "Williams Selyem" },
    { id: "kistler", name: "Kistler" },
    { id: "peter_michael", name: "Peter Michael" },
    { id: "flowers", name: "Flowers" },
    { id: "wayfarer", name: "Wayfarer" },
    { id: "verite", name: "Verité" },
    { id: "devil_proof", name: "Devil Proof" },
    { id: "macauley", name: "Macauley" },
    { id: "paul_hobbs", name: "Paul Hobbs" },
    { id: "st_rose", name: "St. Rose" },
    { id: "carte_blanche", name: "Carte Blanche" },
    { id: "freestone", name: "Freestone" },
    { id: "the_bridge", name: "The Bridge" },
    { id: "legacy", name: "Legacy" },
    { id: "parallel", name: "Parallel" },
    { id: "reuling_vineyard", name: "Reuling Vineyard" },
    { id: "ramey", name: "Ramey" },
    { id: "hartford_court", name: "Hartford Court" },
  ],
  willamette: [
    { id: "ken_wright", name: "Ken Wright" },
    { id: "cristom", name: "Cristom" },
    { id: "penner_ash", name: "Penner-Ash" },
    { id: "nicolasjay", name: "Nicolas-Jay" },
    { id: "shea", name: "Shea" },
    { id: "alloro", name: "Alloro" },
    { id: "patricia_green_cellars", name: "Patricia Green Cellars" },
    { id: "resonance", name: "Résonance" },
    { id: "domaine_drouhin_oregon", name: "Domaine Drouhin Oregon" },
    { id: "brittan_vineyards", name: "Brittan Vineyards" },
    { id: "lavinea", name: "Lavinea" },
    { id: "elevee_winegrowers", name: "Élevée Winegrowers" },
    { id: "ayoub", name: "Ayoub" },
    { id: "domaine_drouhin", name: "Domaine Drouhin" },
    { id: "trisaetum", name: "Trisaetum" },
    { id: "brick_house", name: "Brick House" },
    { id: "bergstrom", name: "Bergström" },
    { id: "the_eyrie_vineyards", name: "The Eyrie Vineyards" },
  ],
  paso_robles: [
    { id: "cordant", name: "Cordant" },
    { id: "golden_triangle", name: "Golden Triangle" },
    { id: "epoch_estate_wines", name: "Epoch Estate Wines" },
    { id: "parrish_family", name: "Parrish Family" },
    { id: "law", name: "Law" },
    { id: "big_basin", name: "Big Basin" },
    { id: "paix_sur_terre", name: "Paix Sur Terre" },
    { id: "michael_gill_cellars", name: "Michael Gill Cellars" },
    { id: "daou", name: "Daou" },
    { id: "jada_vineyard_winery", name: "Jada Vineyard & Winery" },
    { id: "cottonwood_canyon", name: "Cottonwood Canyon" },
    { id: "kukkula", name: "kukkula" },
    { id: "aaron", name: "Aaron" },
    { id: "mooney_family", name: "Mooney Family" },
    { id: "tooth_and_nail", name: "Tooth and Nail" },
  ],
  santa_barbara: [
    { id: "hecho_por_ruben", name: "Hecho por Ruben" },
    { id: "aether_wine_company", name: "Aether Wine Company" },
    { id: "piro", name: "Piro" },
    { id: "cordant", name: "Cordant" },
    { id: "solomon_hills", name: "Solomon Hills" },
    { id: "chigai_takaha", name: "Ch.igai Takaha" },
    { id: "clendenen_family", name: "Clendenen Family" },
    { id: "holus_bolus", name: "Holus Bolus" },
    { id: "chanin", name: "Chanin" },
    { id: "cattleya", name: "Cattleya" },
    { id: "scar_of_the_sea", name: "Scar of the Sea" },
    { id: "tanner_dafoe", name: "Tanner DaFoe" },
    { id: "au_bon_climat", name: "Au Bon Climat" },
    { id: "ryan_cochrane", name: "Ryan Cochrane" },
    { id: "la_voix", name: "La Voix" },
  ],
  finger_lakes: [
    { id: "n_kendall_wines", name: "N. Kendall Wines" },
    { id: "hermann_j_wiemer", name: "Hermann J. Wiemer" },
    { id: "boundary_breaks", name: "Boundary Breaks" },
    { id: "anthony_nappa", name: "Anthony Nappa" },
    { id: "kelby_james_russell", name: "Kelby James Russell" },
    { id: "tierce", name: "Tierce" },
    { id: "keuka_lake_vineyards", name: "Keuka Lake Vineyards" },
    { id: "brooklyn_winery", name: "Brooklyn Winery" },
    { id: "dr_konstantin_frank", name: "Dr. Konstantin Frank" },
    { id: "shaw", name: "Shaw" },
    { id: "red_tail_ridge", name: "Red Tail Ridge" },
    { id: "red_newt_cellars", name: "Red Newt Cellars" },
    { id: "timothy_moore", name: "Timothy Moore" },
    { id: "bloomer_creek", name: "Bloomer Creek" },
    { id: "bellwether", name: "Bellwether" },
  ],
  walla_walla: [
    { id: "horsepower", name: "Horsepower" },
    { id: "quilceda_creek", name: "Quilceda Creek" },
    { id: "cayuse", name: "Cayuse" },
    { id: "doubleback", name: "Doubleback" },
    { id: "no_girls", name: "No Girls" },
    { id: "shoup", name: "Shoup" },
    { id: "la_rata", name: "La Rata" },
    { id: "corliss_estates", name: "Corliss Estates" },
    { id: "b_leighton", name: "B. Leighton" },
    { id: "betz_family", name: "Betz Family" },
    { id: "figgins", name: "Figgins" },
    { id: "leonetti_cellar", name: "Leonetti Cellar" },
    { id: "pirouette", name: "Pirouette" },
    { id: "k_vintners", name: "K Vintners" },
    { id: "gramercy", name: "Gramercy" },
  ],
  stellenbosch: [
    { id: "meerlust", name: "Meerlust" },
    { id: "rust_en_vrede", name: "Rust en Vrede" },
    { id: "thelema", name: "Thelema" },
    { id: "mvemve_raats", name: "Mvemve Raats" },
    { id: "de_toren", name: "De Toren" },
    { id: "kaapzicht", name: "Kaapzicht" },
    { id: "etienne_le_riche", name: "Etienne le Riche" },
    { id: "jordan_stellenbosch", name: "Jordan Stellenbosch" },
    { id: "ernie_els", name: "Ernie Els" },
    { id: "demorgenzon", name: "DeMorgenzon" },
    { id: "starkconde", name: "Stark-Condé" },
    { id: "reyneke", name: "Reyneke" },
    { id: "de_trafford", name: "de Trafford" },
    { id: "glenelly", name: "Glenelly" },
    { id: "kanonkop", name: "Kanonkop" },
    { id: "delheim", name: "Delheim" },
    { id: "teddy_hall", name: "Teddy Hall" },
    { id: "waterford", name: "Waterford" },
  ],
  constantia: [
    { id: "klein_constantia", name: "Klein Constantia" },
    { id: "groot_constantia", name: "Groot Constantia" },
    { id: "constantia_glen", name: "Constantia Glen" },
    { id: "buitenverwachting", name: "Buitenverwachting" },
    { id: "constantia_uitsig", name: "Constantia Uitsig" },
    { id: "steenberg", name: "Steenberg" },
    { id: "silvermist", name: "Silvermist" },
    { id: "eagles_nest", name: "Eagle's Nest" },
    { id: "high_constantia", name: "High Constantia" },
    { id: "constantia_royale", name: "Constantia Royale" },
    { id: "cape_point_vineyards", name: "Cape Point Vineyards" },
    { id: "ambeloui", name: "Ambeloui" },
  ],
  franschhoek: [
    { id: "boekenhoutskloof", name: "Boekenhoutskloof" },
    { id: "bellingham", name: "Bellingham" },
    { id: "chamonix", name: "Chamonix" },
    { id: "dieu_donne", name: "Dieu Donne" },
    { id: "la_motte", name: "La Motte" },
    { id: "grande_provence", name: "Grande Provence" },
    { id: "holden_manz", name: "Holden Manz" },
    { id: "rickety_bridge", name: "Rickety Bridge" },
    { id: "moreson", name: "Moreson" },
    { id: "plaisir_de_franschhoek", name: "Plaisir de Franschhoek" },
    { id: "franschhoek_cellar", name: "Franschhoek Cellar" },
    { id: "rupert_rothschild", name: "Rupert & Rothschild" },
    { id: "haute_cabriere", name: "Haute Cabrière" },
    { id: "lynx", name: "Lynx" },
    { id: "leopards_leap", name: "Leopard's Leap" },
  ],
  swartland: [
    { id: "sadie_family", name: "Sadie Family" },
    { id: "aa_badenhorst_family_wines", name: "A.A. Badenhorst Family Wines" },
    { id: "mullineux", name: "Mullineux" },
    { id: "delaire_graff", name: "Delaire Graff" },
    { id: "terre_brulee", name: "Terre Brûlée" },
    { id: "boekenhoutskloof", name: "Boekenhoutskloof" },
    { id: "spice_route", name: "Spice Route" },
    { id: "lammershoek", name: "Lammershoek" },
    { id: "painted_wolf", name: "Painted Wolf" },
    { id: "riebeek_cellars", name: "Riebeek Cellars" },
    { id: "porseleinberg", name: "Porseleinberg" },
    { id: "david_nadia", name: "David & Nadia" },
    { id: "intellego", name: "Intellego" },
    { id: "kalmoesfontein", name: "Kalmoesfontein" },
    { id: "rall", name: "Rall" },
  ],
  walker_bay: [
    { id: "creation", name: "Creation" },
    { id: "ataraxia", name: "Ataraxia" },
    { id: "hamilton_russell", name: "Hamilton Russell" },
    { id: "beaumont", name: "Beaumont" },
    { id: "luddite", name: "Luddite" },
    { id: "bouchard_finlayson", name: "Bouchard Finlayson" },
    { id: "southern_right", name: "Southern Right" },
    { id: "restless_river", name: "Restless River" },
    { id: "newton_johnson", name: "Newton Johnson" },
    { id: "storm_wines", name: "Storm Wines" },
    { id: "gabrielskloof", name: "Gabriëlskloof" },
    { id: "sumaridge", name: "Sumaridge" },
    { id: "whale_haven", name: "Whale Haven" },
    { id: "la_vierge", name: "La Vierge" },
    { id: "crystallum", name: "Crystallum" },
  ],
  paarl: [
    { id: "vilafonte", name: "Vilafonté" },
    { id: "avondale", name: "Avondale" },
    { id: "bellingham", name: "Bellingham" },
    { id: "glen_carlou", name: "Glen Carlou" },
    { id: "fairview", name: "Fairview" },
    { id: "graham_beck", name: "Graham Beck" },
    { id: "plaisir_de_merle", name: "Plaisir De Merle" },
    { id: "kwv", name: "KWV" },
    { id: "backsberg", name: "Backsberg" },
    { id: "niel_joubert", name: "Niel Joubert" },
    { id: "tormentoso", name: "Tormentoso" },
    { id: "wamakersvallei", name: "Wamakersvallei" },
    { id: "babylonstoren", name: "Babylonstoren" },
    { id: "boschendal", name: "Boschendal" },
    { id: "veenwouden", name: "Veenwouden" },
  ],
  mendoza: [
    { id: "terrazas_de_los_andes", name: "Terrazas de los Andes" },
    { id: "trapiche", name: "Trapiche" },
    { id: "susana_balbo", name: "Susana Balbo" },
    { id: "ltu", name: "LTU" },
    { id: "cheval_des_andes", name: "Cheval des Andes" },
    { id: "flechas_de_los_andes", name: "Flechas de los Andes" },
    { id: "teho", name: "TeHo" },
    { id: "serca", name: "Serca" },
    { id: "superuco", name: "Superuco" },
    { id: "bodega_catena_zapata", name: "Bodega Catena Zapata" },
    { id: "riglos", name: "Riglos" },
    { id: "el_enemigo", name: "El Enemigo" },
    { id: "achavalferrer", name: "Achaval-Ferrer" },
    { id: "puramun", name: "Puramun" },
    { id: "vistalba", name: "Vistalba" },
    { id: "alpasion", name: "Alpasión" },
    { id: "revancha", name: "Revancha" },
    { id: "vina_cobos", name: "Viña Cobos" },
  ],
  salta: [
    { id: "el_esteco", name: "El Esteco" },
    { id: "colome", name: "Colomé" },
    { id: "bodega_etchart", name: "Bodega Etchart" },
    { id: "san_pedro_de_yacochuya", name: "San Pedro de Yacochuya" },
    { id: "michel_torino", name: "Michel Torino" },
    { id: "piattelli", name: "Piattelli" },
    { id: "puna", name: "Puna" },
    { id: "bodega_tacuil", name: "Bodega Tacuil" },
    { id: "bodega_mounier", name: "Bodega Mounier" },
    { id: "amalaya", name: "Amalaya" },
    { id: "domingo_hermanos", name: "Domingo Hermanos" },
    { id: "rio_lindo", name: "Río Lindo" },
    { id: "bad_brothers", name: "Bad Brothers" },
    { id: "felix_lavaque", name: "Félix Lavaque" },
    { id: "bodega_nanni", name: "Bodega Nanni" },
  ],
  patagonia_ar: [
    { id: "bodega_del_fin_del_mundo", name: "Bodega del Fin del Mundo" },
    { id: "humberto_canale", name: "Humberto Canale" },
    { id: "noemia", name: "Noemia" },
    { id: "chacra", name: "Chacra" },
    { id: "bodega_patritti", name: "Bodega Patritti" },
    { id: "familia_schroeder", name: "Familia Schroeder" },
    { id: "secreto_patagonico", name: "Secreto Patagónico" },
    { id: "aniello", name: "Aniello" },
    { id: "otronia", name: "Otronia" },
    { id: "manos_negras", name: "Manos Negras" },
    { id: "bodegas_del_rio_negro", name: "Bodegas del Río Negro" },
    { id: "contra_corriente", name: "Contra Corriente" },
  ],
  maipo: [
    { id: "concha_y_toro", name: "Concha y Toro" },
    { id: "almaviva", name: "Almaviva" },
    { id: "carmen", name: "Carmen" },
    { id: "santa_rita", name: "Santa Rita" },
    { id: "undurraga", name: "Undurraga" },
    { id: "cousino_macul", name: "Cousiño-Macul" },
    { id: "antiyal", name: "Antiyal" },
    { id: "haras_de_pirque", name: "Haras de Pirque" },
    { id: "william_fevre_chile", name: "William Fèvre Chile" },
    { id: "perez_cruz", name: "Pérez Cruz" },
    { id: "tarapaca", name: "Tarapacá" },
    { id: "dona_javiera", name: "Doña Javiera" },
    { id: "ventisquero", name: "Ventisquero" },
    { id: "canepa", name: "Canepa" },
    { id: "terramater", name: "TerraMater" },
  ],
  colchagua: [
    { id: "montes", name: "Montes" },
    { id: "casa_lapostolle", name: "Casa Lapostolle" },
    { id: "clos_apalta", name: "Clos Apalta" },
    { id: "viu_manent", name: "Viu Manent" },
    { id: "luis_felipe_edwards", name: "Luis Felipe Edwards" },
    { id: "santa_cruz", name: "Santa Cruz" },
    { id: "neyen", name: "Neyen" },
    { id: "casa_silva", name: "Casa Silva" },
    { id: "bisquertt", name: "Bisquertt" },
    { id: "los_vascos", name: "Los Vascos" },
    { id: "estampa", name: "Estampa" },
    { id: "koyle", name: "Koyle" },
    { id: "montgras", name: "MontGras" },
    { id: "siegel", name: "Siegel" },
    { id: "las_ninas", name: "Las Niñas" },
  ],
  casablanca: [
    { id: "kingston_family", name: "Kingston Family" },
    { id: "emiliana", name: "Emiliana" },
    { id: "villard", name: "Villard" },
    { id: "veramonte", name: "Veramonte" },
    { id: "casas_del_bosque", name: "Casas del Bosque" },
    { id: "matetic", name: "Matetic" },
    { id: "indolmita", name: "Indomita" },
    { id: "vina_mar", name: "Viña Mar" },
    { id: "william_cole", name: "William Cole" },
    { id: "loma_larga", name: "Loma Larga" },
    { id: "bodegas_re", name: "Bodegas RE" },
    { id: "casa_marin", name: "Casa Marín" },
  ],
  aconcagua: [
    { id: "errazuriz", name: "Errázuriz" },
    { id: "sena", name: "Seña" },
    { id: "von_siebenthal", name: "Von Siebenthal" },
    { id: "san_esteban", name: "San Esteban" },
    { id: "arboleda", name: "Arboleda" },
    { id: "vina_san_pedro", name: "Viña San Pedro" },
    { id: "panquehue", name: "Panquehue" },
    { id: "san_rafael", name: "San Rafael" },
    { id: "vina_von_siebenthal", name: "Viña Von Siebenthal" },
    { id: "ritual", name: "Ritual" },
    { id: "caliterra", name: "Caliterra" },
    { id: "aconcagua_wines", name: "Aconcagua Wines" },
  ],
  barossa: [
    { id: "henschke", name: "Henschke" },
    { id: "peter_lehmann", name: "Peter Lehmann" },
    { id: "hickinbotham", name: "Hickinbotham" },
    { id: "glaetzer", name: "Glaetzer" },
    { id: "standish", name: "Standish" },
    { id: "casella", name: "Casella" },
    { id: "nashwauk", name: "Nashwauk" },
    { id: "kay_brothers", name: "Kay Brothers" },
    { id: "kaesler", name: "Kaesler" },
    { id: "langmeil", name: "Langmeil" },
    { id: "torbreck", name: "Torbreck" },
    { id: "john_duval_wines", name: "John Duval Wines" },
    { id: "paxton", name: "Paxton" },
    { id: "clarendon_hills", name: "Clarendon Hills" },
    { id: "angove", name: "Angove" },
    { id: "tapanappa", name: "TapaNappa" },
    { id: "hentley_farm", name: "Hentley Farm" },
  ],
  mclaren: [
    { id: "hickinbotham", name: "Hickinbotham" },
    { id: "nashwauk", name: "Nashwauk" },
    { id: "kay_brothers", name: "Kay Brothers" },
    { id: "paxton", name: "Paxton" },
    { id: "angove", name: "Angove" },
    { id: "kilikanoon", name: "Kilikanoon" },
    { id: "alpha_crucis", name: "Alpha Crucis" },
    { id: "cape_barren", name: "Cape Barren" },
    { id: "chapel_hill", name: "Chapel Hill" },
    { id: "ess_see", name: "Ess & See" },
    { id: "forefathers", name: "Forefathers" },
    { id: "mitolo", name: "Mitolo" },
    { id: "thistledown", name: "Thistledown" },
    { id: "fox_creek", name: "Fox Creek" },
    { id: "two_hands", name: "Two Hands" },
  ],
  yarra: [
    { id: "yarra_yering", name: "Yarra Yering" },
    { id: "ben_haines", name: "Ben Haines" },
    { id: "strathewen_hills", name: "Strathewen Hills" },
    { id: "giant_steps", name: "Giant Steps" },
    { id: "robert_oatley", name: "Robert Oatley" },
    { id: "yeringberg", name: "Yeringberg" },
    { id: "mount_mary", name: "Mount Mary" },
    { id: "marlargo", name: "Marlargo" },
    { id: "innocent_bystander", name: "Innocent Bystander" },
    { id: "yering_station", name: "Yering Station" },
    { id: "sticks", name: "Sticks" },
    { id: "shoofly", name: "Shoofly" },
    { id: "long_flat", name: "Long Flat" },
    { id: "coldstream_hills", name: "Coldstream Hills" },
    { id: "de_bortoli", name: "De Bortoli" },
  ],
  margaret_river: [
    { id: "cherubino", name: "Cherubino" },
    { id: "vasse_felix", name: "Vasse Felix" },
    { id: "cloudburst", name: "Cloudburst" },
    { id: "cullen", name: "Cullen" },
    { id: "moss_wood", name: "Moss Wood" },
    { id: "wise", name: "Wise" },
    { id: "frankland_estate", name: "Frankland Estate" },
    { id: "leeuwin_estate", name: "Leeuwin Estate" },
    { id: "howard_park", name: "Howard Park" },
    { id: "ringbolt", name: "Ringbolt" },
    { id: "cape_mentelle", name: "Cape Mentelle" },
    { id: "plantagenet", name: "Plantagenet" },
    { id: "robert_oatley", name: "Robert Oatley" },
    { id: "franklin_tate", name: "Franklin Tate" },
    { id: "wildberry_estate", name: "Wildberry Estate" },
  ],
  hunter: [
    { id: "heritage_road", name: "Heritage Road" },
    { id: "brokenwood", name: "Brokenwood" },
    { id: "tyrrells", name: "Tyrrell's" },
    { id: "wyndham_estate", name: "Wyndham Estate" },
    { id: "hope_estate", name: "Hope Estate" },
    { id: "mcguigan", name: "McGuigan" },
    { id: "rosemount", name: "Rosemount" },
    { id: "lake_fold", name: "Lake's Folly" },
    { id: "mount_pleasant", name: "Mount Pleasant" },
    { id: "drayton", name: "Drayton's" },
    { id: "tamburlaine", name: "Tamburlaine" },
    { id: "scarborough", name: "Scarborough" },
    { id: "lindemans", name: "Lindemans" },
    { id: "de_iuliis", name: "De Iuliis" },
    { id: "pepper_tree", name: "Pepper Tree" },
  ],
  coonawarra: [
    { id: "angove", name: "Angove" },
    { id: "penfolds", name: "Penfolds" },
    { id: "penley_estate", name: "Penley Estate" },
    { id: "jim_barry", name: "Jim Barry" },
    { id: "petaluma", name: "Petaluma" },
    { id: "parker", name: "Parker" },
    { id: "di_giorgio_family_wines", name: "Di Giorgio Family Wines" },
    { id: "yalumba", name: "Yalumba" },
    { id: "balnaves_of_coonawarra", name: "Balnaves of Coonawarra" },
    { id: "katnook_estate", name: "Katnook Estate" },
    { id: "wynns_coonawarra_estate", name: "Wynns Coonawarra Estate" },
    { id: "jacobs_creek", name: "Jacob's Creek" },
    { id: "long_flat", name: "Long Flat" },
    { id: "hollick", name: "Hollick" },
    { id: "angoves", name: "Angove's" },
  ],
  marlborough: [
    { id: "kim_crawford", name: "Kim Crawford" },
    { id: "oyster_bay", name: "Oyster Bay" },
    { id: "greywacke", name: "Greywacke" },
    { id: "sineann", name: "Sineann" },
    { id: "loveblock", name: "Loveblock" },
    { id: "kumeu_river", name: "Kumeu River" },
    { id: "jackson_estate", name: "Jackson Estate" },
    { id: "esk_valley", name: "Esk Valley" },
    { id: "craggy_range", name: "Craggy Range" },
    { id: "seresin", name: "Seresin" },
    { id: "babich", name: "Babich" },
    { id: "dog_point", name: "Dog Point" },
    { id: "forefathers", name: "Forefathers" },
    { id: "cloudy_bay", name: "Cloudy Bay" },
    { id: "eradus", name: "Eradus" },
    { id: "villa_maria", name: "Villa Maria" },
    { id: "nautilus", name: "Nautilus" },
  ],
  central_otago: [
    { id: "quartz_reef", name: "Quartz Reef" },
    { id: "etude", name: "Etude" },
    { id: "felton_road", name: "Felton Road" },
    { id: "loveblock", name: "Loveblock" },
    { id: "akarua", name: "Akarua" },
    { id: "carrick", name: "Carrick" },
    { id: "rockburn", name: "Rockburn" },
    { id: "cloudy_bay", name: "Cloudy Bay" },
    { id: "two_paddocks", name: "Two Paddocks" },
    { id: "prophets_rock", name: "Prophet's Rock" },
    { id: "amisfield", name: "Amisfield" },
    { id: "peregrine", name: "Peregrine" },
    { id: "valli", name: "Valli" },
    { id: "paritua", name: "Paritua" },
    { id: "rippon", name: "Rippon" },
  ],
  hawkes_bay: [
    { id: "squawking_magpie", name: "Squawking Magpie" },
    { id: "te_mata", name: "Te Mata" },
    { id: "cypress", name: "Cypress" },
    { id: "trinity_hill", name: "Trinity Hill" },
    { id: "dry_river", name: "Dry River" },
    { id: "clearview", name: "Clearview" },
    { id: "esk_valley", name: "Esk Valley" },
    { id: "craggy_range", name: "Craggy Range" },
    { id: "babich", name: "Babich" },
    { id: "villa_maria", name: "Villa Maria" },
    { id: "decibel", name: "Decibel" },
    { id: "sacred_hill", name: "Sacred Hill" },
    { id: "te_awa", name: "Te Awa" },
    { id: "paritua", name: "Paritua" },
    { id: "stonecroft", name: "Stonecroft" },
  ],
  douro: [
    { id: "quinta_do_vale_meo", name: "Quinta do Vale Meão" },
    { id: "quinta_do_vesuvio", name: "Quinta do Vesuvio" },
    { id: "quinta_vale_dona_maria", name: "Quinta Vale Dona Maria" },
    { id: "quinta_do_noval", name: "Quinta do Noval" },
    { id: "casa_ferreirinha", name: "Casa Ferreirinha" },
    { id: "apegadas_quinta_velha", name: "Apegadas Quinta Velha" },
    { id: "wine_soul", name: "Wine & Soul" },
    { id: "quinta_de_so_jose", name: "Quinta de São José" },
    { id: "niepoort", name: "Niepoort" },
    { id: "emilio_moro", name: "Emilio Moro" },
    { id: "dows", name: "Dow's" },
    { id: "prats_symington_lda", name: "Prats & Symington LDA" },
    { id: "poeira", name: "Poeira" },
    { id: "quinta_da_foz", name: "Quinta da Foz" },
    { id: "quinta_dos_aciprestes", name: "Quinta dos Aciprestes" },
  ],
  alentejo: [
    { id: "moucho", name: "Mouchão" },
    { id: "sogrape", name: "Sogrape" },
    { id: "cartuxa", name: "Cartuxa" },
    { id: "companhia_das_quintas", name: "Companhia das Quintas" },
    { id: "quinta_do_quetzal", name: "Quinta do Quetzal" },
    { id: "herdade_do_esporo", name: "Herdade do Esporão" },
    { id: "dona_mariajulio_bastos", name: "Dona Maria-Júlio Bastos" },
    { id: "herdade_do_rocim", name: "Herdade do Rocim" },
    { id: "ribafreixo", name: "Ribafreixo" },
    { id: "monte_da_penha", name: "Monte da Penha" },
    { id: "herdade_dos_machados", name: "Herdade dos Machados" },
    { id: "alente", name: "Alente" },
    { id: "herdade_do_perdigo", name: "Herdade do Perdigão" },
    { id: "j_portugal_ramos", name: "J. Portugal Ramos" },
    { id: "caves_alianca", name: "Caves Aliança" },
  ],
  dao: [
    { id: "alvaro_castro", name: "Alvaro Castro" },
    { id: "casa_anadia", name: "Casa Anadia" },
    { id: "vinha_paz", name: "Vinha Paz" },
    { id: "quinta_do_perdigo", name: "Quinta do Perdigão" },
    { id: "quinta_de_lemos", name: "Quinta de Lemos" },
    { id: "sogrape", name: "Sogrape" },
    { id: "fontes_da_cunha", name: "Fontes da Cunha" },
    { id: "quinta_das_marias", name: "Quinta das Marias" },
    { id: "pedra_cancela", name: "Pedra Cancela" },
    { id: "casa_da_passarella", name: "Casa da Passarella" },
    { id: "magnum_vinhos", name: "Magnum Vinhos" },
    { id: "quinta_do_sobral", name: "Quinta do Sobral" },
    { id: "ideal_drinks", name: "Ideal Drinks" },
    { id: "antonio_lopes_ribeiro", name: "Antonio Lopes Ribeiro" },
    { id: "boas_quintas", name: "Boas Quintas" },
  ],
  vinho_verde: [
    { id: "niepoort", name: "Niepoort" },
    { id: "provam", name: "Provam" },
    { id: "anselmo_mendes", name: "Anselmo Mendes" },
    { id: "quinta_de_soalheiro", name: "Quinta de Soalheiro" },
    { id: "quinta_do_ameal", name: "Quinta do Ameal" },
    { id: "ideal_drinks", name: "Ideal Drinks" },
    { id: "quinta_do_portal", name: "Quinta do Portal" },
    { id: "broadbent", name: "Broadbent" },
    { id: "do_sul", name: "Dão Sul" },
    { id: "global_wines", name: "Global Wines" },
    { id: "messias", name: "Messias" },
    { id: "quinta_de_santiago", name: "Quinta de Santiago" },
    { id: "jose_maria_da_fonseca", name: "José Maria da Fonseca" },
    { id: "casa_do_valle", name: "Casa do Valle" },
    { id: "caves_da_montanha", name: "Caves da Montanha" },
  ],
  mosel: [
    { id: "joh_jos_prum", name: "Joh. Jos. Prüm" },
    { id: "fritz_haag", name: "Fritz Haag" },
    { id: "egon_muller", name: "Egon Müller" },
    { id: "dr_loosen", name: "Dr. Loosen" },
    { id: "reichsgraf_von_kesselstatt", name: "Reichsgraf von Kesselstatt" },
    { id: "sa_prum", name: "S.A. Prüm" },
    { id: "markus_molitor", name: "Markus Molitor" },
    { id: "maximin_grunhauser", name: "Maximin Grünhäuser" },
    { id: "dr_hermann", name: "Dr. Hermann" },
    { id: "dr_h_thanisch_erben_mullerburggraef", name: "Dr. H. Thanisch (Erben Müller-Burggraef)" },
    { id: "st_urbanshof", name: "St. Urbans-Hof" },
    { id: "kirsten", name: "Kirsten" },
    { id: "schloss_saarstein", name: "Schloss Saarstein" },
    { id: "hansenlauer", name: "Hansen-Lauer" },
    { id: "karl_erbes", name: "Karl Erbes" },
  ],
  rheingau: [
    { id: "robert_weil", name: "Robert Weil" },
    { id: "schloss_johannisberger", name: "Schloss Johannisberger" },
    { id: "schloss_reinhartshausen", name: "Schloss Reinhartshausen" },
    { id: "weingut_hans_bausch", name: "Weingut Hans Bausch" },
    { id: "balthasar_ress", name: "Balthasar Ress" },
    { id: "domdechant_werner", name: "Domdechant Werner" },
    { id: "johannishof", name: "Johannishof" },
    { id: "schloss_vollrads", name: "Schloss Vollrads" },
    { id: "toni_jost", name: "Toni Jost" },
    { id: "prinz", name: "Prinz" },
    { id: "august_kesseler", name: "August Kesseler" },
    { id: "peter_jakob_kuhn", name: "Peter Jakob Kühn" },
    { id: "baron_knyphausen", name: "Baron Knyphausen" },
    { id: "dr_nagler", name: "Dr. Nägler" },
    { id: "carl_ehrhard", name: "Carl Ehrhard" },
  ],
  pfalz: [
    { id: "friedrich_becker", name: "Friedrich Becker" },
    { id: "mullercatoir", name: "Müller-Catoir" },
    { id: "okonomierat_rebholz", name: "Ökonomierat Rebholz" },
    { id: "dr_burklinwolf", name: "Dr. Bürklin-Wolf" },
    { id: "geh_rat_dr_von_bassermannjordan", name: "Geh. Rat Dr. von Bassermann-Jordan" },
    { id: "gerd_anselmann", name: "Gerd Anselmann" },
    { id: "eugen_muller", name: "Eugen Müller" },
    { id: "august_kesseler", name: "August Kesseler" },
    { id: "karl_schaefer", name: "Karl Schaefer" },
    { id: "nauerthgnagy", name: "Nauerth-Gnägy" },
    { id: "pfluger", name: "Pflüger" },
    { id: "a_christmann", name: "A. Christmann" },
    { id: "fitzritter", name: "Fitz-Ritter" },
    { id: "von_buhl", name: "Von Buhl" },
    { id: "villa_wolf", name: "Villa Wolf" },
  ],
  baden: [
    { id: "bernhard_huber", name: "Bernhard Huber" },
    { id: "wohrle", name: "Wöhrle" },
    { id: "franz_keller", name: "Franz Keller" },
    { id: "fischer", name: "Fischer" },
    { id: "huber", name: "Huber" },
    { id: "weingut_stadt_lahr", name: "Weingut Stadt Lahr" },
    { id: "ziereisen", name: "Ziereisen" },
    { id: "salwey", name: "Salwey" },
    { id: "weingut_dr_heger", name: "Weingut Dr. Heger" },
    { id: "stigler", name: "Stigler" },
    { id: "weingut_abril", name: "Weingut Abril" },
    { id: "weingut_schloss_neuweier", name: "Schloss Neuweier" },
  ],
  rheinhessen: [
    { id: "wittmann", name: "Wittmann" },
    { id: "thorle", name: "Thörle" },
    { id: "kuhlinggillot", name: "Kühling-Gillot" },
    { id: "prinz_salm", name: "Prinz Salm" },
    { id: "rheingraf", name: "Rheingraf" },
    { id: "gunderloch", name: "Gunderloch" },
    { id: "gm_machmer", name: "G&M; Machmer" },
    { id: "thomas_schmitt", name: "Thomas Schmitt" },
    { id: "weingut_georg_albrecht_schneider", name: "Weingut Georg Albrecht Schneider" },
    { id: "weingut_liebfrauenstift", name: "Weingut Liebfrauenstift" },
    { id: "gustav_adolf_schmitt", name: "Gustav Adolf Schmitt" },
    { id: "weinreich", name: "Weinreich" },
    { id: "dr_volkmar", name: "Dr. Volkmar" },
    { id: "dachshund", name: "Dachshund" },
    { id: "binz", name: "Binz" },
  ],
  wachau: [
    { id: "domane_wachau", name: "Domäne Wachau" },
    { id: "franz_hirtzberger", name: "Franz Hirtzberger" },
    { id: "fx_pichler", name: "F.X. Pichler" },
    { id: "rudi_pichler", name: "Rudi Pichler" },
    { id: "prager", name: "Prager" },
    { id: "nikolaihof", name: "Nikolaihof" },
    { id: "alzinger", name: "Alzinger" },
    { id: "weingut_knoll", name: "Weingut Knoll" },
    { id: "josef_jamek", name: "Josef Jamek" },
    { id: "pichler_krutzler", name: "Pichler-Krutzler" },
    { id: "tegernseerhof", name: "Tegernseerhof" },
    { id: "lagler", name: "Lagler" },
    { id: "johann_donabaum", name: "Johann Donabaum" },
    { id: "jager", name: "Jäger" },
    { id: "eder", name: "Eder" },
  ],
  kamptal: [
    { id: "emmerich_knoll", name: "Emmerich Knoll" },
    { id: "eichinger", name: "Eichinger" },
    { id: "kracher", name: "Kracher" },
    { id: "proidl", name: "Proidl" },
    { id: "malat", name: "Malat" },
    { id: "schloss_gobelsburg", name: "Schloss Gobelsburg" },
    { id: "brundlmayer", name: "Bründlmayer" },
    { id: "hiedler", name: "Hiedler" },
    { id: "jurtschitsch", name: "Jurtschitsch" },
    { id: "ingrid_groiss", name: "Ingrid Groiss" },
    { id: "weinrieder", name: "Weinrieder" },
    { id: "sohm_kracher", name: "Sohm & Kracher" },
    { id: "bernhard_ott", name: "Bernhard Ott" },
    { id: "loimer", name: "Loimer" },
    { id: "stadlmann", name: "Stadlmann" },
  ],
  burgenland: [
    { id: "krutzler", name: "Krutzler" },
    { id: "heidi_schrock", name: "Heidi Schröck" },
    { id: "kracher", name: "Kracher" },
    { id: "jalits", name: "Jalits" },
    { id: "heinrich", name: "Heinrich" },
    { id: "heribert_bayer", name: "Heribert Bayer" },
    { id: "prieler", name: "Prieler" },
    { id: "steindorfer", name: "Steindorfer" },
    { id: "sohm_kracher", name: "Sohm & Kracher" },
    { id: "nittnaus_anita_und_hans", name: "Nittnaus Anita und Hans" },
    { id: "uwe_schiefer", name: "Uwe Schiefer" },
    { id: "schwarz_wein", name: "Schwarz Wein" },
    { id: "gerhard_pittnauer", name: "Gerhard Pittnauer" },
    { id: "kollwentz", name: "Kollwentz" },
    { id: "hans_igler", name: "Hans Igler" },
  ],
};

export const VARIETALS = [
  { id: "cabernet_sauvignon", name: "Cabernet Sauvignon", color: "red" },
  { id: "merlot", name: "Merlot", color: "red" },
  { id: "pinot_noir", name: "Pinot Noir", color: "red" },
  { id: "syrah", name: "Syrah / Shiraz", color: "red" },
  { id: "malbec", name: "Malbec", color: "red" },
  { id: "tempranillo", name: "Tempranillo", color: "red" },
  { id: "sangiovese", name: "Sangiovese", color: "red" },
  { id: "nebbiolo", name: "Nebbiolo", color: "red" },
  { id: "grenache", name: "Grenache / Garnacha", color: "red" },
  { id: "zinfandel", name: "Zinfandel", color: "red" },
  { id: "pinotage", name: "Pinotage", color: "red" },
  { id: "mourvedre", name: "Mourvèdre", color: "red" },
  { id: "cabernet_franc", name: "Cabernet Franc", color: "red" },
  { id: "petit_verdot", name: "Petit Verdot", color: "red" },
  { id: "chardonnay", name: "Chardonnay", color: "white" },
  { id: "sauvignon_blanc", name: "Sauvignon Blanc", color: "white" },
  { id: "riesling", name: "Riesling", color: "white" },
  { id: "pinot_grigio", name: "Pinot Grigio / Pinot Gris", color: "white" },
  { id: "chenin_blanc", name: "Chenin Blanc", color: "white" },
  { id: "viognier", name: "Viognier", color: "white" },
  { id: "gruner_veltliner", name: "Grüner Veltliner", color: "white" },
  { id: "albarino", name: "Albariño", color: "white" },
  { id: "gewurztraminer", name: "Gewürztraminer", color: "white" },
  { id: "semillon", name: "Sémillon", color: "white" },
  { id: "muscadet", name: "Muscadet / Melon de Bourgogne", color: "white" },
  { id: "vermentino", name: "Vermentino", color: "white" },
];
